name: entao_sql
description: SQLite and PostgreSQL.
repository: https://github.com/yangentao/entao_sql
homepage: https://github.com/yangentao/entao_sql
version: 0.1.0

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  # path: ^1.9.0
  sqlite3: ^3.1.1
  postgres: ^3.5.9

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
