name: entao_sql
description: SQLite and PostgreSQL.
repository: https://github.com/yangentao/entao_sql
homepage: https://github.com/yangentao/entao_sql
version: 0.1.0

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  # path: ^1.9.0
  sqlite3: ^3.1.1
  postgres: ^3.5.9
#  mysql1: ^0.20.0
#  mysql1_ext: ^0.0.4
  mysql_client_plus: ^0.1.2
  println: ^1.0.4
  entao_dutil: ^2.3.1
  entao_log: ^1.2.8
  entao_lint: ^1.0.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
